# Generated by Django 4.1.2 on 2023-02-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, null=True, unique=True, verbose_name='Token')),
                ('user_name', models.CharField(max_length=150, null=True, verbose_name='User_name')),
                ('user_email', models.EmailField(max_length=254, null=True)),
                ('google_id', models.CharField(default=None, max_length=254, null=True)),
                ('facebook_id', models.CharField(default=None, max_length=254, null=True)),
                ('apple_id', models.CharField(default=None, max_length=254, null=True)),
                ('user_profile_pic', models.URLField(max_length=254, null=True)),
                ('user_phone_no', models.CharField(max_length=15, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_guest', models.BooleanField(default=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Register at')),
            ],
        ),
    ]
